### ISSUE TITLE
MILESTONE: Choose a tech stack

### ISSUE THREAD

**Issue by jeturcotte** [sarl-hackerspace/ingredient.guru#1]
- [ ] REQ: We must have a database technology (fewer is better, but not STRICTLY one alone.)
- [ ] REQ: We must have a cacheing technology
- [ ] REQ: We must choose a deployment architecture
- [ ] REQ: We must choose an API standard
- [ ] REQ: We must choose an authentication standard
- [ ] REQ: We must choose a primary API engine language (again, not strictly one, but as few as possible)
- [ ] REQ: We must choose a UI engine

**Comment by jeturcotte** [comment]
To help propel people, I will itemize MY preferences:

- MariaDB (sql is fiiiiine and maria is free from oracle machinations.)  I'd also happily explore Neo4j, but am not comfortable enough to actually recommend it outright.
- Redis seems obvious to me, here.
- I suggest service oriented and deployable by anyone who wants to run a local/regional node for a few bucks a month off anything like openshift or heroku or aws or azure whatever they want.  Scale by free distribution and collaborative standards rather than centralized expense.
- I'm happy with REST and GRPC
- OAuth?
- If it were just me on my own, I'd use perl's mojolicious.  I ASSUME most folk in this group would prefer django or flask, which I'm not interested in fighting about.
- Not a VERY strong decision... presumably angular or react.
