### ISSUE TITLE
MILESTONE - Basic Unit Testing

### ISSUE THREAD

**Issue by jeturcotte** [sarl-hackerspace/ingredient.guru#11]
Right, so now let's change focus for a bit and introduce some unit testing to our proto-application before we get too far in and lose our minds trying to do testing for ALL of it.  Particularly savvy outfits often write tests FIRST (before any code) to help guide developers to producing the intended product, but also to basically document the whole idea.  That's a level of sophistication most places don't achieve, tbh... but is wonderful to behold when it is in place.  (full disclosure... I've yet to do it myself, but sure would like to.)

- [x] RESEARCH: Learn about unit testing (in general / via raku).
  - [x] https://docs.perl6.org/language/testing seeeeeems like a good start, as a basic built in testing layer for perl6/raku overall.
  - [x] Quickly see if anyone in the community has built out a more fully featured one, just for informational purposes.
- [x] TASK: Test the internal non-visible guts of the application as it currently stands
  - [x] Write a test that verifies that the application is responding at all.
    - [x] This might include ADDING an API endpoint to the application that acts as a 'heartbeat' ... when you call it the server responds saying basically either 'yep, I'm running' or doesn't respond, and therefore is broken.  Then add the test to simply check for this heartbeat and pass the test on correct response.
- [x] TASK: Test the creation of an account ( re: https://github.com/sarl-hackerspace/ingredient.guru/issues/6 ) and account verification (re: https://github.com/sarl-hackerspace/ingredient.guru/issues/10 )
  - [x] Ensure that submitting all the needed data results in a successfully created account
  - [x] Ensure that submitting insufficient data results in an error response from the server
  - [x] Ensure that submitting the wrong kind of information results in an error from the server
- [x] TASK: Test the usefulness of authentication ( re: https://github.com/sarl-hackerspace/ingredient.guru/issues/7 )
  - [x] Ensure that submitting an authentication attempt with the correct credentials results in being 'logged in'
  - [x] Ensure that submitting incorrect authentication details will result in a rejection
  - LATER, when we have more screens that should ONLY be accessible to authenticated individuals, we will test that they CANNOT be reached without it (but that's later.)

Note the above of somewhat vague in part because I still need to catch up with what you've done and in part because you should try to asses what would make a good test.  Still, if you look at the code and see a function that does a specific thing, it's a good subject for testing.

Ask questions (preferably in the comments.)

**Comment by ajbuchholz** [comment]
Ok. So you would like us to start testing the application and documenting this? I am slightly confused as too what you would like us to do this afternoon and Thursday. We were planning on beginning documentation for CRO. If you have the time to create a checklist like in other issues we would greatly appreciate that.

**Comment by jeturcotte** [comment]
I'm writing it out still... it'll show up here as I save incrementally save it

**Comment by jeturcotte** [comment]
Don't abandon cro docs in the meantime

**Comment by ajbuchholz** [comment]
Got it.

**Comment by ajbuchholz** [comment]
We have been looking into test-driven development. So far we generally understand it because of its similarities to Doctest with python. We hope to see you tonight!

**Comment by jeturcotte** [comment]
note: https://dev.to/lancew/tdd-and-cro-in-perl6-land-20g1

**Comment by jeturcotte** [comment]
How'd things go the last week?

**Comment by ajbuchholz** [comment]
We just wanted to keep you updated. Last week we took a break and worked on our Django servers. Today and Thursday we will start to look into very basic tests, specificallly some of the stuff we did last Thursday. When we come back from winter break expect to see more commits.

**Comment by jeturcotte** [comment]
Not a problem; I'm rolling at your class's pace

**Comment by ajbuchholz** [comment]
I have begun making progress outside of class. Just commited some of the latest tests.

**Comment by ajbuchholz** [comment]
So we will talk Thursday "Write a test that verifies that the application is responding at all." I understand what I have to do, but I just want to know if there is a specific way we should do it. I will probably be writing more tests this afternoon to determine whether a session is created successfully.

**Comment by jelkner** [comment]
This is great news, Adrian!  As I've mentioned to you several times before,
learning the discipline of TDD is far more important than learning
particular programming language.  If you can learn this practice using Raku
now, you'll be all set to learn Django next Summer.

Jeff
