### ISSUE TITLE
MILESTONE: Download and transform free nutritional data from USDA

### ISSUE THREAD

**Issue by jeturcotte** [sarl-hackerspace/ingredient.guru#2]
Feel free to break the following into smaller tasks

- [ ] SPEC: Go to the source, get the .zip download
  - URL: https://ndb.nal.usda.gov/ndb/ ... go to downloads and get both the BFPD and SR
  - NOTE: From a very quick examination, the 'legacy' SR data looks like the better option, but that's to be determined.
- [ ] SPEC: Examine and study the contents of the data to learn how to filter out prepared meals and leave behind/import only ingredients
  - [ ] SPEC: We consider prepared meals and processed items no good
  - [ ] SPEC: We consider raw ingredients like oils, meats, vegetables, et cetera, as desirable
- [ ] SPEC: Examine and study the structure of the data to get an understanding of where the data we want actually is
  - [ ] REQ: First, let's report on what data the two OFFER and discuss that
- [ ] SPEC: Propose and discuss a proposal or two for NEW schemas that will store the parts from the chosen data set that we wish to keep or even extrapolate
- [ ] SPEC: Write a script or scripts to import the wanted subset of the data into our new structures.

**Comment by jeturcotte** [comment]
Anyhow; let's use this to have remote conversation about this task

**Comment by jeturcotte** [comment]
Not that it's late by any means, but I haven't really heard from anyone nor have I been able to identify the three students from among the list of group members.  @mattva01 or @jelkner ... anyone on there you recogize that I can add so that we don't fail to communicate?

**Comment by jeturcotte** [comment]
How's it going, all?  Do communicate here a time or two a week, as things happen.
