### ISSUE TITLE
MILESTONE -- Registration

### ISSUE THREAD

**Issue by jeturcotte** [sarl-hackerspace/ingredient.guru#6]
Let's get started by building up a CRO service in and around the idea of a user account.

- [x] First, get a CRO service started
  - [x] Make sure it has access to a SQLite database (we'll upgrade to postgres down the road when it is called for)
    - [x] Make sure the database is set up to be persistent between runnings of the service
    - [x] Make sure there is an 'account' table
      - [x] Make sure it has a column for numerical incrementing ID
      - [x] Make sure it has a column for username
      - [x] Make sure it has a column for password
        - [x] BONUS: Find a way to encrypt this password so a download of the database won't compromise people's passwords (not required in early days but would be important to final product)
      - [x] Make sure it has a column for email address
      - [x] Make sure there's a date and time column for when the account was created
  - [x] Make sure it has a get -> function to / (homepage) ... 
    - [x] Make sure this homepage has a <form></form> with:
      - [x] Username
      - [x] Password
      - [x] Email Address
    - [x] And a submit button that'll map to a post -> /account/ endpoint in the CRO service
  - [x] Make sure there is a post -> /account/ endpoint that will receive the form data
    - [x] Establish a connection to the SQLite database and write the contents of the form to the database
    - [x] Make sure it adds a unique ID at the same time the user is created
    - [x] Make sure it adds the DATE and TIME to the table as 'created' (the form would not send this)
    - [x] Package up the details about the new user (including id and created date) and send it back to the browser as JSON
  - [x] Make sure there is a get -> /account/<username>/ endpoint that will show the full details of a user with the username <username>
    - [x] If the username exists, send the details back as JSON
    - [x] if the username does not exist, send back a 404 not found

**Comment by jeturcotte** [comment]
There's a lot more to do in and around users, but this is quite a few things just to start with, so we'll worry about all that later.

**Comment by jelkner** [comment]
Thanks, Josh!  This looks like a helpful guide for Peter and Adrian to follow.  I'm committed to letting this be their learning path for class, combined with Learning Perl 6 (https://www.learningperl6.com/), which will provide an organized foundation to programming in the language.

**Comment by PeterY18** [comment]
10/7/19 
Today we started got a working cro to run. We created a form in HTML to take user data. A simple database was also created. The problem we are currently dealing with is getting the data from the user in the browser to into the database

**Comment by HermesTheDev** [comment]
10/7/19 Evening Update (After School)
Created two separate links to Sign-In and Register with forms. (Although the links don't work, because we are unsure on how to link them). Database connection has been established and created a table "accounts" with ID, Username, Password, and Email. 

TODO
1. Link other HTML Files, currently static page, needs to be dynamic. (We asked the Cro Devs how to do this)

2. Learn how to retrieve inputted info from HTML and input it into the database.

**Comment by jeturcotte** [comment]
Excellent, btw; my own staff aren't updating their tickets this well...

**Comment by HermesTheDev** [comment]
10/8/19 Update (After School)

I figured out how to create a home page with links to a sign in and register page. We still need to get the information and input it into the database. We will try to work on this tomorrow, although I think we will end up needing help Thursday Night doing this.

**Comment by HermesTheDev** [comment]
10/9/19 Update (Morning)
https://cro.services/docs/intro/spa-with-cro
This link gives instructions that don't make much sense to me. However, I'm pretty sure this is what we want. Peter & I will keep looking into it, this afternoon in class.

**Comment by jeturcotte** [comment]
Hmm, it is inevitable; buuuuut, we can go a fair way with dumb forms to wring out our back end.  For a single page app, look to react or angular... but that's a whole other level of learning.

**Comment by HermesTheDev** [comment]
10/9/19 Update (Class)
We did it. We have a post statement that retrieves the info entered in an HTML form and prints them. We are now trying to input those values into the database. I am going to try to figure this out tonight.

**Comment by HermesTheDev** [comment]
10/9/19 Update (Evening) 
All the tasks have been accomplished. I am looking into hashing the password, which shouldn't be too hard. You can create an account, and it will cause an error if the username already exists. You still can't sign in. That will be something that we can work on tomorrow evening. 

* If you would like you can take a look. Simply do Cro Run 😄 *
https://gitlab.com/Hermes_/perl6-laboratory/tree/crotest

**Comment by jeturcotte** [comment]
This does need to be in this repo, though... doesn't bar you from having it in gitlab also; you can have more than one remote origin.

**Comment by fcrisafulli-dev** [comment]
The merge request on master should fills that final bubble.

**Comment by fcrisafulli-dev** [comment]
Did not realize this was for the CRO server portion

**Comment by fcrisafulli-dev** [comment]
Check feature/CRO sign-in-test for the hashes use link
localhost:20000/login
